/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfazG;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import manejoBD.metodosBD;

/**
 *
 * @author tulre
 */
public class DetallesCompras extends javax.swing.JFrame {
    metodosBD m = new metodosBD();
    int metodo = 0;
    String idCompra;

    /** Creates new form Vendedores */
    public DetallesCompras(String id) {
        initComponents();
        idCompra = id;
        jLabel2.setText("Detalles de la Compra: " + idCompra);
        iniciar();
    }
    
    private void iniciar(){
        limpiar(jTable1);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String sql = "select * from DetallesCompras where IdCompra='" + idCompra + "'";
        m.llenarTablaD(sql, modelo, 4);
    }
    
    private void limpiar(JTable tablas){
        while(tablas.getRowCount() > 0){
            ((DefaultTableModel) tablas.getModel()).removeRow(0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo de Proveedores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdProducto", "ContidadPC", "CostoP", "SubTotalC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Detalles de la Compra: ");

        jButton1.setText("Actualizar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("IdProducto:");

        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("CantidadPC:");

        jTextField1.setEnabled(false);

        jTextField2.setEnabled(false);

        jButton7.setText("Confirmar");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Cancelar");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setText("CostoP:");

        jLabel5.setText("SubTotalC:");

        jTextField3.setEnabled(false);

        jTextField4.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(20, 20, 20)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(55, 55, 55)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jButton3)
                                        .addGap(50, 50, 50)
                                        .addComponent(jButton4)
                                        .addGap(1, 1, 1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7)
                                        .addGap(55, 55, 55)))
                                .addComponent(jButton8)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jTextField1.setEnabled(true);
        jTextField1.requestFocus();
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        metodo = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jTextField1.setEnabled(true);
        jTextField1.requestFocus();
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        metodo = 2;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton7.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField2.requestFocus();
        jTextField3.setEnabled(true);
        metodo = 3;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?", "!Alerta¡",JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(res == JOptionPane.YES_OPTION) {
            String idProducto = jTextField1.getText();
            String sql = "delete from DetallesCompras where IdCompra='" + idCompra + "' and IdProducto='" + idProducto + "'";
            int band = m.eliminar(sql);
            if (band != 1)
                JOptionPane.showMessageDialog(null, "Detalle NO eliminado, Revise por favor");
            else {
                JOptionPane.showMessageDialog(null, "Detalle Eliminado Exitosamente ");
                jButton2.setEnabled(true);
                jButton3.setEnabled(true);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField1.setEnabled(false);
                jTextField2.setEnabled(false);
                jButton7.setEnabled(false);
                jButton8.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String sql = "update Compras set Total=(select sum(SubTotalC) from DetallesCompras where IdCompra='" + idCompra + "') where IdCompra='" + idCompra + "'";
        int band = m.modificar(sql);
        if (band != 1){
            JOptionPane.showMessageDialog(null, "Total no calculado por que no existen detalles");
            sql = "update Compras set Total=0 where IdCompra='" + idCompra + "'";
            m.modificar(sql);
        }else {
            JOptionPane.showMessageDialog(null, "Total de compra calculado");
        }
        super.dispose();
        Compras co = new Compras();
        co.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String idProducto, cantidadPC, costoP, subTotalC, sql;
        if(metodo == 1){
            idProducto = jTextField1.getText();
            cantidadPC = jTextField2.getText();
            costoP = jTextField3.getText();
            
            sql = "select Stock from Productos where IdProducto='" + idProducto + "'";
            Object stock = m.buscarA(sql, "Stock");
            sql = "select CantidadP from Productos where IdProducto='" + idProducto + "'";
            Object cant = m.buscarA(sql, "CantidadP");
            if(!stock.toString().isEmpty()){
                if((Double.parseDouble(stock.toString()) + Double.parseDouble(cantidadPC)) <= Double.parseDouble(cant.toString())){
                    sql = "update Productos set Stock=" + (Double.parseDouble(stock.toString()) + Double.parseDouble(cantidadPC)) + " where IdProducto='" + idProducto + "'";
                    m.modificar(sql);
                    subTotalC = String.valueOf((Double.parseDouble(cantidadPC) * Double.parseDouble(costoP)));
                    sql = "insert into DetallesCompras values('" + idCompra + "','" + idProducto + "'," + cantidadPC + "," + costoP + "," + subTotalC + ")";
                    int band = m.agregar(sql);
                    if (band != 1)
                        JOptionPane.showMessageDialog(null, "Detalle NO registrado, Revise por favor");
                    else {
                        JOptionPane.showMessageDialog(null, "Detalle Registrado con Éxito ");
                        jButton2.setEnabled(true);
                        jButton3.setEnabled(true);
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jTextField1.setEnabled(false);
                        jTextField2.setEnabled(false);
                        jTextField3.setEnabled(false);
                        jButton7.setEnabled(false);
                        jButton8.setEnabled(false);
                    }
                }else {
                    JOptionPane.showMessageDialog(null, "No es posible agregar la compra por exceso del producto");
                }
            }else {
                    JOptionPane.showMessageDialog(null, "Producto no encontrado");
            }
        }else if(metodo == 2) {
            idProducto = jTextField1.getText();
            sql = "select * from DetallesCompras where IdCompra='" + idCompra + "' and IdProducto='" + idProducto + "'";
            Object[] datos = m.buscarD(sql, 4);
            if(datos[0].toString().equals("")) {
                jTextField1.setText("");
                jTextField2.setText("");
                JOptionPane.showMessageDialog(null, "Detalle NO encontrado");
            }else {
                jTextField1.setText(datos[0].toString());
                jTextField2.setText(datos[1].toString());
                jTextField3.setText(datos[2].toString());
                jTextField4.setText(datos[3].toString());
                jTextField1.setEnabled(false);
                jTextField2.setEnabled(false);
                jTextField3.setEnabled(false);
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
                jButton7.setEnabled(false);
            }
        }else if(metodo == 3) {
            idProducto = jTextField1.getText();
            cantidadPC = jTextField2.getText();
            costoP = jTextField3.getText();
            
            sql = "select Stock from Productos where IdProducto='" + idProducto + "'";
            Object stock = m.buscarA(sql, "Stock");
            sql = "select CantidadP from Productos where IdProducto='" + idProducto + "'";
            Object cant = m.buscarA(sql, "CantidadP");
            sql = "select CantidadPC from DetallesCompras where IdCompra='" + idCompra + "' and IdProducto='" + idProducto +"'";
            Object cantPC = m.buscarA(sql, "CantidadPC");
            if(!stock.toString().isEmpty()){
                if((Double.parseDouble(stock.toString()) + Double.parseDouble(cantidadPC) - Double.parseDouble(cantPC.toString())) <= Double.parseDouble(cant.toString())){
                    sql = "update Productos set Stock=" + (Double.parseDouble(stock.toString()) + Double.parseDouble(cantidadPC) - Double.parseDouble(cantPC.toString())) + " where IdProducto='" + idProducto + "'";
                    m.modificar(sql);
                    subTotalC = String.valueOf(Double.parseDouble(cantidadPC) * Double.parseDouble(costoP));
                    sql = "update DetallesCompras set CantidadPC=" + cantidadPC + ", CostoP=" + costoP + ", SubTotalC=" + subTotalC + " where IdCompra='" + idCompra + "' and IdProducto='" + idProducto + "'";
                    int band = m.modificar(sql);
                    if (band != 1)
                        JOptionPane.showMessageDialog(null, "Detalle NO modificado, Revise por favor");
                    else {
                        JOptionPane.showMessageDialog(null, "Detalle modificado con Éxito ");
                        jButton2.setEnabled(true);
                        jButton3.setEnabled(true);
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jTextField4.setText("");
                        jTextField1.setEnabled(false);
                        jTextField2.setEnabled(false);
                        jTextField3.setEnabled(false);
                        jTextField4.setEnabled(false);
                        jButton7.setEnabled(false);
                        jButton8.setEnabled(false);
                    }
                }else {
                    JOptionPane.showMessageDialog(null, "No es posible modificar la compra por exceso del producto");
                }
            }else {
                    JOptionPane.showMessageDialog(null, "Producto no encontrado");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
